version: '3.3'

services:
    db:
        image: postgres:9.6
        volumes:
            - library-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: library-db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5439:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build: .
        depends_on:
            db:
                condition: service_healthy
        ports:
            - 8080:8080
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/library-db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres

volumes:
    library-db-data:  # Define the named volume